# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# © 2023 Floorp Projects & Contributors

on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        default: true

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "latest"

    - name: Clone 🧬
      uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Configure sccache
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    # - name: Setup Rust 🦀
    #   run: |
    #     rustup default nightly
    #     rustup target add aarch64-unknown-linux-gnu
    #     export CARGO_INCREMENTAL=0

    - name: Setup Rust 🦀
      run: |
        rustup default stable
        rustup target add aarch64-unknown-linux-gnu
        export CARGO_INCREMENTAL=0

    - name: Allocate swap
      run: |
        echo "Before:"
        free -h
        df -h

        sudo swapoff /mnt/swapfile || true
        sudo rm /mnt/swapfile || true
        sudo fallocate -l 20G /mnt/swapfile
        sudo chmod 600 /mnt/swapfile
        sudo mkswap /mnt/swapfile
        sudo swapon /mnt/swapfile

        sudo apt autoremove -y
        sudo apt clean
        sudo rm -rf ./git /home/linuxbrew /usr/share/dotnet /usr/local/lib/android /usr/local/graalvm
        sudo rm -rf /usr/local/share/powershell /usr/local/share/chromium /opt/ghc /usr/local/share/boost
        sudo rm -rf /etc/apache2 /etc/nginx /usr/local/share/chrome_driver /usr/local/share/edge_driver
        sudo rm -rf /usr/local/share/gecko_driver /usr/share/java /usr/share/miniconda /usr/local/share/vcpkg

        echo "After:"
        free -h
        df -h

    - name: Setup 🪛
      run: |
        cd $GITHUB_WORKSPACE
        git submodule update --remote
        cp ./.github/workflows/mozconfigs/linux64-aarch64.mozconfig mozconfig
        cp -r ./noraneko/gecko/branding/* ./browser/branding/
        sudo apt install msitools -y

        echo "mk_add_options 'export RUSTC_WRAPPER=/home/runner/.mozbuild/sccache/sccache'" >> mozconfig
        echo "mk_add_options 'export CCACHE_CPP2=yes'" >> mozconfig
        echo "ac_add_options --with-ccache=/home/runner/.mozbuild/sccache/sccache" >> mozconfig
        echo "mk_add_options 'export SCCACHE_GHA_ENABLED=on'" >> mozconfig

        if [[ $GHA_debug == 'true' ]]; then
          echo "ac_add_options --enable-debug" >> mozconfig
          git apply --ignore-space-change --reject --ignore-whitespace .github/patches/dev/*.patch
        fi

        # Chrome Format
        echo "ac_add_options --enable-chrome-format=flat" >> mozconfig
        # Enable Flat Package

        ./mach --no-interactive bootstrap --application-choice browser
      env:
        GHA_debug: ${{ inputs.debug }}

    - name: Mach Configure
      run: |
        ./mach configure

    - name: Build 🔨
      run: |
        ./mach build
        ./mach package
        rm -rf ~/.cargo

    # Publish START
    - name: Extract Package 📦
      run: |
        cd obj-aarch64-unknown-linux-gnu/dist/
        mkdir ~/output
        tar xjf noraneko-*.tar.bz2 -C ~/output

    - name: Publish Package 🎁
      uses: actions/upload-artifact@v4
      with:
        name: noraneko-linux-aarch64-dev
        path: ~/output/noraneko/
    # Publish END
